spring:
  profiles:
  datasource:
    url: jdbc:postgresql://localhost:5432/pi
    username: tigler
    password: parol_prostoiy
    driverClassName: 'org.postgresql.Driver'
  jpa:
    properties:
      hibernate:
        dialect: 'org.hibernate.dialect.PostgreSQLDialect'